### ISSUE TITLE
Log parsing fails on Windows with MikTeX

### ISSUE THREAD

**Issue by dan-masek** [mbr/latex#16]
When running on Windows and using MikTeX, the filenames that are part of error messages look as follows:

```
c:/some/path/tmpcn8jq0.latex:12: Package pdftex
.def Error: File `./images/vs_logo_old.png' not found.
```

Specifically, they begin with drive letter followed by a colon. As such the current regular expression doesn't detect them.

The following monkey patch of the regexp mitigates the problem:
```
import latex.errors
latex.errors.LATEX_ERR_RE = re.compile(r'(?P<filename>([a-z]:)?[^:]+):(?P<line>[0-9]+):\s*(?P<error>.*)')
```

**Comment by mbr** [comment]
Hopefully, this fixed it. Please try with the new file/version to let me know, then I'll cut a new release.

**Comment by dan-masek** [comment]
Sorry for the delay. I tested it and it works. Thanks

**Comment by mbr** [comment]
Try version 0.6.3.
