### ISSUE TITLE
Possible to hide Windows command window (cmd) when building?

### ISSUE THREAD

**Issue by richbl** [mbr/latex#19]
First off, your package has been working quite well. Thanks for creating it.

I'm usually a Linux person, but I have a need to create a Windows-based LaTeX report-building application using Python/GTK and Jinja2.

What I want to do is let the user pick some build options via GUI, call into your latex package to do the compile, and then present the completed PDF to the user.

At the moment, when the call is made to build_pdf(), a separate process is created to start the latexmk (using MikTeX) build, which flashes a Windows command window (cmd).

Is there any way to hide the command window during this build process?

As I'm not familar Windows coding, I'm not even sure if this is controllable from your package, or if it's a larger issue at an architectural level.

Thanks

RIch

**Comment by richbl** [comment]
I ended up resolving this at a meta-level, that is, via the use of a monkey-patch made to calls into `subprocess.Popen()`. See my post to SO for details here: https://stackoverflow.com/questions/42143939/python-subprocess-calls-into-matplotlib-on-windows

**Comment by mbr** [comment]
Sorry, can't help here. I'm surprised that subprocess opens up a cmd Window. I have never used `subcommand` on Windows myself.
