### ISSUE TITLE
Adding/Including External files to build directory

### ISSUE THREAD

**Issue by stoberblog** [mbr/latex#34]
Hi, I'm trying to include an image in my python based latex file however, I've realised that since the latex file is build in a temporary location, it is unable to include images that are in a relative location to the python script.

Is there any way to easily get around this? I'd prefer to not use a full path, as it makes the script less portable.

One way I thought could be the simplest solution would be to have a function that allows adding files to the temporary build space (be that a symbolic link or a copy)

**Comment by jberends** [comment]
you could override the `PdfLatexBuilder` class yourself and alter the `build_pdf()` method.

i did this exactly for this reason. I added an option to `__init__` to provide a workspace `Path` where to build the pdf and put the media included in the latex in. The media I place inside the workspace `Path` before calling `build_pdf()` of the initialised `MyPdfLatexBuilder`.

I altered the first line of the `build_pdf` method.
