### ISSUE TITLE
reference to github on http://pythonhosted.org/latex/

### ISSUE THREAD

**Issue by fariza** [mbr/latex#5]
Hi again

There is not a single reference to the github repo from the documentation page.
It is a little bit confusing, given that searching for latex gives hundreds of results

**Comment by fariza** [comment]
The same goes for data,

**Comment by mbr** [comment]
I never considered that, to be honest. Normally, the chain works like this:

PyPI: Has a link to the docs (pythonhosted.org/pkg-name) *and* the github page.
GitHub: Links to the PyPI page or the docs.

I'll see if I can add this easily later on.

**Comment by fariza** [comment]
That is what we normally think, but after a search in google I landed in the pythonhosted.org/pkg-name
Without a way of knowing what was the real name of the pipy package (pyLatex is the other package), and without a way to go to the github
